naver:
  url:
    search:
      local: https://openapi.naver.com/v1/search/local.json
      image: https://openapi.naver.com/v1/search/image
  client:
    id: 02877vWYc5DWO3fxk0ax
    secret: OR2IP0JU80
